// src/lib/components/AudioControls.svelte
<script lang="ts">
	import { togglePause } from '$lib/utils';
	import { onMount, onDestroy } from 'svelte';

	export let audio: HTMLAudioElement;
	export let fullscreenContainer: HTMLElement | null = null;

	let isPlaying = audio.paused;
	let currentTime = 0;
	let duration = 0;
	let seekValue = 0;
	let isDragging = false;
	let isFullscreen = false;

	function formatTime(seconds: number): string {
		if (isNaN(seconds)) return '00:00';

		const minutes = Math.floor(seconds / 60);
		const remainingSeconds = Math.floor(seconds % 60);

		return `${minutes.toString().padStart(2, '0')}:${remainingSeconds.toString().padStart(2, '0')}`;
	}

	function toggleFullscreen() {
		if (!fullscreenContainer) return;

		if (!document.fullscreenElement) {
			fullscreenContainer.requestFullscreen().catch((err) => {
				console.error('Error attempting to enable fullscreen:', err);
			});
		} else {
			document.exitFullscreen();
		}
	}

	function handleFullscreenChange() {
		isFullscreen = !!document.fullscreenElement;
	}

	function handleSeek() {
		if (audio && !isNaN(duration) && duration > 0) {
			audio.currentTime = (seekValue / 100) * duration;
		}
	}

	function handleSeekStart() {
		isDragging = true;
	}

	function handleSeekEnd() {
		isDragging = false;
		handleSeek();
	}

	function updateTime() {
		if (!isDragging && audio) {
			currentTime = audio.currentTime;
			if (duration > 0) {
				seekValue = (currentTime / duration) * 100;
			}
		}
	}

	function setupEventListeners() {
		if (audio) {
			audio.addEventListener('play', () => {
				isPlaying = true;
			});
			audio.addEventListener('pause', () => {
				isPlaying = false;
			});
			audio.addEventListener('timeupdate', updateTime);
			audio.addEventListener('durationchange', () => {
				duration = audio.duration;
				updateTime();
			});
			audio.addEventListener('loadedmetadata', () => {
				duration = audio.duration;
				updateTime();
			});

			isPlaying = !audio.paused;
			currentTime = audio.currentTime;
			duration = audio.duration || 0;
			if (duration > 0) {
				seekValue = (currentTime / duration) * 100;
			}
		}
	}

	function cleanupEventListeners() {
		if (audio) {
			audio.removeEventListener('play', () => {
				isPlaying = true;
			});
			audio.removeEventListener('pause', () => {
				isPlaying = false;
			});
			audio.removeEventListener('timeupdate', updateTime);
			audio.removeEventListener('durationchange', () => {
				duration = audio.duration;
				updateTime();
			});
			audio.removeEventListener('loadedmetadata', () => {
				duration = audio.duration;
				updateTime();
			});
		}
	}

	onMount(() => {
		setupEventListeners();
		document.addEventListener('fullscreenchange', handleFullscreenChange);
	});

	onDestroy(() => {
		cleanupEventListeners();
		document.removeEventListener('fullscreenchange', handleFullscreenChange);
	});

	// Watch for audio prop changes
	$: if (audio) {
		cleanupEventListeners();
		setupEventListeners();
	}
</script>

<div class="flex w-full flex-wrap items-center gap-2 rounded bg-slate-700 p-2">
	<button
		class="flex h-10 w-10 items-center justify-center rounded-full bg-blue-500 text-white transition-colors hover:bg-blue-600 focus:outline-none"
		on:click={() => togglePause(audio)}
		aria-label={isPlaying ? 'Pause' : 'Play'}
	>
		{#if isPlaying}
			<svg class="h-5 w-5 fill-current" viewBox="0 0 24 24">
				<rect x="6" y="4" width="4" height="16" />
				<rect x="14" y="4" width="4" height="16" />
			</svg>
		{:else}
			<svg class="h-5 w-5 fill-current" viewBox="0 0 24 24">
				<polygon points="5,3 19,12 5,21" />
			</svg>
		{/if}
	</button>

	<div class="relative h-5 flex-grow">
		<div class="absolute w-full">
			<input
				type="range"
				min="0"
				max="100"
				bind:value={seekValue}
				step="0.001"
				on:input={handleSeek}
				on:mousedown={handleSeekStart}
				on:mouseup={handleSeekEnd}
				on:touchstart={handleSeekStart}
				on:touchend={handleSeekEnd}
				class="absolute z-10 h-2 w-full cursor-pointer appearance-none bg-transparent"
			/>
		</div>
		<div class="absolute top-1/2 right-0 left-0 h-2 -translate-y-1/2 rounded bg-gray-300"></div>
		<div
			class="absolute top-1/2 left-0 h-2 -translate-y-1/2 rounded bg-blue-500"
			style="width: {seekValue}%"
		></div>
	</div>
	<div class="min-w-[100px] text-center font-mono text-sm">
		<span>{formatTime(currentTime)}</span>
		<span class="mx-1">/</span>
		<span>{formatTime(duration)}</span>
	</div>
	<button
		class="flex h-10 w-10 items-center justify-center rounded-full bg-slate-600 text-white transition-colors hover:bg-slate-500 focus:outline-none"
		on:click={toggleFullscreen}
		aria-label={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
		disabled={!fullscreenContainer}
	>
		{#if isFullscreen}
			<svg class="h-5 w-5 fill-current" viewBox="0 0 24 24">
				<path d="M5 16h3v3h2v-5H5v2zm3-8H5v2h5V5H8v3zm6 11h2v-3h3v-2h-5v5zm2-11V5h-2v5h5V8h-3z" />
			</svg>
		{:else}
			<svg class="h-5 w-5 fill-current" viewBox="0 0 24 24">
				<path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z" />
			</svg>
		{/if}
	</button>
</div>

// app/src/components/AudioControls.tsx
import { useState, useEffect, useCallback } from "react";
import { Flex, IconButton, Slider, Text } from "@radix-ui/themes";
import {
  PlayIcon,
  PauseIcon,
  EnterFullScreenIcon,
  ExitFullScreenIcon,
  GearIcon,
} from "@radix-ui/react-icons";

function formatTime(seconds: number): string {
  if (isNaN(seconds)) return "00:00";
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = Math.floor(seconds % 60);
  return `${minutes.toString().padStart(2, "0")}:${remainingSeconds.toString().padStart(2, "0")}`;
}

function togglePause(audio: HTMLAudioElement) {
  if (audio.paused) {
    audio.play();
  } else {
    audio.pause();
  }
}

export function AudioControls({
  audio,
  fullscreenContainer,
  onOptionsClick,
}: {
  audio: HTMLAudioElement;
  fullscreenContainer: HTMLElement | null;
  onOptionsClick: () => void;
}) {
  const [isPlaying, setIsPlaying] = useState(!audio.paused);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(audio.duration || 0);
  const [seekValue, setSeekValue] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);

  const updateTime = useCallback(() => {
    if (!isDragging) {
      setCurrentTime(audio.currentTime);
      if (audio.duration > 0) {
        setSeekValue((audio.currentTime / audio.duration) * 100);
      }
    }
  }, [audio, isDragging]);

  useEffect(() => {
    const onPlay = () => setIsPlaying(true);
    const onPause = () => setIsPlaying(false);
    const onDuration = () => {
      setDuration(audio.duration);
      updateTime();
    };

    audio.addEventListener("play", onPlay);
    audio.addEventListener("pause", onPause);
    audio.addEventListener("timeupdate", updateTime);
    audio.addEventListener("durationchange", onDuration);
    audio.addEventListener("loadedmetadata", onDuration);

    setIsPlaying(!audio.paused);
    setCurrentTime(audio.currentTime);
    setDuration(audio.duration || 0);

    return () => {
      audio.removeEventListener("play", onPlay);
      audio.removeEventListener("pause", onPause);
      audio.removeEventListener("timeupdate", updateTime);
      audio.removeEventListener("durationchange", onDuration);
      audio.removeEventListener("loadedmetadata", onDuration);
    };
  }, [audio, updateTime]);

  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(!!document.fullscreenElement);
    };
    document.addEventListener("fullscreenchange", handleFullscreenChange);
    return () => document.removeEventListener("fullscreenchange", handleFullscreenChange);
  }, []);

  function handleSeek(value: number) {
    if (!isNaN(duration) && duration > 0) {
      audio.currentTime = (value / 100) * duration;
    }
  }

  function toggleFullscreen() {
    if (!fullscreenContainer) return;
    if (!document.fullscreenElement) {
      fullscreenContainer.requestFullscreen().catch((err) => {
        console.error("Error attempting to enable fullscreen:", err);
      });
    } else {
      document.exitFullscreen();
    }
  }

  return (
    <Flex
      align="center"
      gap="3"
      p="2"
      px="3"
      style={{
        backgroundColor: "color-mix(in oklab, var(--accent-3) 70%, transparent)",
        borderTop: "1px solid var(--accent-a5)",
        backdropFilter: "blur(8px)",
      }}
    >
      <IconButton
        size="3"
        radius="full"
        variant="solid"
        onClick={() => togglePause(audio)}
        aria-label={isPlaying ? "Pause" : "Play"}
      >
        {isPlaying ? <PauseIcon /> : <PlayIcon />}
      </IconButton>

      <Flex flexGrow="1" align="center">
        <Slider
          size="2"
          value={[seekValue]}
          min={0}
          max={100}
          step={0.001}
          onValueChange={(values) => {
            const val = values[0];
            setSeekValue(val);
            handleSeek(val);
          }}
          onPointerDown={() => setIsDragging(true)}
          onPointerUp={() => setIsDragging(false)}
        />
      </Flex>

      <Text
        size="2"
        color="gray"
        style={{ fontFamily: "var(--code-font-family)", minWidth: 100 }}
        align="center"
      >
        {formatTime(currentTime)} / {formatTime(duration)}
      </Text>

      <IconButton
        size="3"
        radius="full"
        variant="soft"
        onClick={toggleFullscreen}
        aria-label={isFullscreen ? "Exit fullscreen" : "Enter fullscreen"}
        disabled={!fullscreenContainer}
      >
        {isFullscreen ? <ExitFullScreenIcon /> : <EnterFullScreenIcon />}
      </IconButton>

      <IconButton
        size="3"
        radius="full"
        variant="soft"
        onClick={onOptionsClick}
        aria-label="Open options"
      >
        <GearIcon />
      </IconButton>
    </Flex>
  );
}
